plugins { id 'com.android.application' }

android {
    namespace 'com.aarthivishakha.androidapp'
    compileSdk 33
    defaultConfig {
        applicationId 'com.aarthivishakha.androidapp'
        minSdk 21
        targetSdk 33
        versionCode 1
        versionName '1.0'
        testInstrumentationRunner 'androidx.test.runner.AndroidJUnitRunner'
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    buildTypes { release { minifyEnabled false } }
    testOptions { unitTests.returnDefaultValues = true }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.5'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.1'
}
